config/routes.rb
Syllabus::Application.routes.draw do

  get "welcome/index"
  

  root 'welcome#index'

  
  get "admin" => "admin#index"
  get "admin/logout" => "admin#logout"
  post "admin/login" => "admin#login"
  
  resources :images  
  
  resources :products do
    resources :images    
  end

  

  
  get ':action' => 'static#:action'
    
end

app/models/image.rb
class Image < ActiveRecord::Base
  
  belongs_to :product  
  has_attached_file :image, :styles => { :original => "600x600>", :medium => "300x300>", :thumb => "100x100>" }, :default_style => :original, :default_url => "/images/:style/missing.png"
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  
  has_many :images
  has_attached_file :image, :styles => { :original => "600x600>", :medium => "300x300>", :thumb => "100x100>" }, :default_style => :original, :default_url => "/images/:style/missing.png"  
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index

  end

  def login
    password = params[:password]
    
    if password == '7797'
      session[:admin] = 'yes'
    end
    redirect_to :admin
  end
  
  def logout
    session.delete(:admin);
    redirect_to :admin
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :admin?
  
  def admin?
    @_admin = session[:admin] != nil    
  end
  
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    product_id = params[:product_id]
    
    if product_id
      @images = Image.where(product_id: product_id)
    else
      @images = Image.all
    end
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)
    
    @image.product_id = params[:product_id]
    
    respond_to do |format|
      if @image.save
        format.html {
          redirect_to :back
          # redirect_to @image, notice: 'Image was successfully created.'
          }
        format.json { render action: 'show', status: :created, location: @image }
      else
        format.html { render action: 'new' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html {
          # redirect_to @image, notice: 'Image was successfully updated.' 
          redirect_to :back 
        }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:image, :product_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    cat = params[:cat]
    season = params[:season]


    where = {}

    if cat
      if season
        if admin?
          @products = Product.where(category: cat, season: season).order('display_order ASC')
        else
          @products = Product.where(hidden: false, category: cat, season: season).order('display_order ASC')
        end
      else
        if admin?
          @products = Product.where(category: cat).order('display_order ASC')
        else
          @products = Product.where(hidden: false, category: cat).order('display_order ASC')
        end
      end
    else
      if season
        if admin?
          @products = Product.where(season: season).order('display_order ASC')
        else
          @products = Product.where(hidden: false, season: season).order('display_order ASC')
        end
      else
        if admin?
          @products = Product.all.order('display_order ASC')
        else
          @products = Product.all.where(hidden: false).order('display_order ASC')
        end
      end
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :category, :season, :image, :display_order, :hidden)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    if mobile_device?    
      redirect_to :products
    end    
  end
  
  def mobile_device?
    if session[:mobile_param]
      session[:mobile_param] == "1"
    else
      request.user_agent =~ /Mobile|webOS/
    end
  end
    
end
  

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  
  def categoryTitle(cat)
    
    title = 'collection'
    
    case cat
    when 100
      title = 'evening clutch'
    when 110
      title = 'convertible clutch'
    when 200
      title = 'convertible tote shoulder'
    when 300
      title = 'belt'
    end
    
    title
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/_form.html.erb
<%= form_tag(:controller => "admin", :action => "login") do %>

<div class="form-inline">
  <div class="form-group">
    <label class="sr-only" for="InputPassword">Password</label>
    <input type="password" name="password" class="form-control" id="InputPassword" placeholder="Password">
  </div>
  <button type="submit" class="btn btn-default">Sign in</button>
</div>

<% end %>

app/views/admin/index.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<% if @_admin %>
		관리자로 로그인 하였습니다.
		<a href="/admin/logout"><button class="btn btn-default">Sign out</button></a>
		<% else %>
		<%= render :partial => 'form' %>
		<% end %>
	</div>
	
	<div class="panel-body">
	</div>
</div>

app/views/images/_form.html.erb
<%= form_for @image, :html => { :class => 'form-horizontal' } do |f| %>


	<%= image_tag @image.image.url(:thumb) %>

  <div class="control-group">
    <%= f.label 'image', :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :image, :class => 'file_field' %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                images_path, :class => 'btn' %>
  </div>
<% end %>

app/views/images/edit.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/index.html.erb
<%- model_class = Image -%>

<div class="panel">
	<div class="panel-body">
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:thumbnail) %></th>
      <th><%= model_class.human_attribute_name(:image_file_name) %></th>
      <th><%= model_class.human_attribute_name(:image_file_size) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= link_to image.id, image_path(image) %></td>
		<td><%= image_tag image.image.url(:thumb) %></td>        
        <td><%= image.image_file_name %></td>
        <td><%= image.image_file_size %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_image_path(image), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      image_path(image),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<!-- <%= link_to t('.new', :default => t("helpers.links.new")),
            new_image_path,
            :class => 'btn btn-primary' %> -->
      </div>      
</div>

app/views/images/new.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/show.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<%= image_tag @image.image.url(:thumb) %>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:product_id) %>:</strong></dt>
  <dd><%= @image.product_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image_file_name) %>:</strong></dt>
  <dd><%= @image.image_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image_content_type) %>:</strong></dt>
  <dd><%= @image.image_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image_file_size) %>:</strong></dt>
  <dd><%= @image.image_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image_updated_at) %>:</strong></dt>
  <dd><%= @image.image_updated_at %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              images_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_image_path(@image), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              image_path(@image),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><%= content_for?(:title) ? yield(:title) : "Syllabus" %></title>
		<%= csrf_meta_tags %>

		<%= javascript_include_tag "application", :cache => false %>

		<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
		<!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
		<![endif]-->

		<%= stylesheet_link_tag "application", :media => "all" %>

		<!-- For third-generation iPad with high-resolution Retina display: -->
		<!-- Size should be 144 x 144 pixels -->
		<%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

		<!-- For iPhone with high-resolution Retina display: -->
		<!-- Size should be 114 x 114 pixels -->
		<%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

		<!-- For first- and second-generation iPad: -->
		<!-- Size should be 72 x 72 pixels -->
		<%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

		<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
		<!-- Size should be 57 x 57 pixels -->
		<%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

		<!-- For all other devices -->
		<!-- Size should be 32 x 32 pixels -->
		<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

	</head>

	<body>

		<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
			<div class="container">
				<div class="separator"></div>
				<div class="navbar-header">
					<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a href="../" class="navbar-brand"><%= image_tag 'BRANDLOGO.png' %></a>
				</div>
				<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
					<ul class="nav navbar-nav">
						<li>
							<a href="/philosophy">Brand Philosophy</a>
						</li>
						<li>
							<a href="/designer">Designer</a>
						</li>

						<li class="<%= controller.controller_name == 'products' ? 'active' : '' %> dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Collections <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li>
									<%= link_to "ALL", "/products" %>
								</li>
								<li class="divider"></li>
								<li>
									<%= link_to "EVENING CLUTCH", "/products?cat=100" %>
								</li>
								<li>
									<%= link_to "CONVERTIBLE TOTE SHOULDER", "/products?cat=200" %>
								</li>
								<li>
									<%= link_to "CONVERTIBLE CLUTCH / PURSE", "/products?cat=110" %>
								</li>
								<li>
									<%= link_to "BELTS", "/products?cat=300" %>
								</li>
							</ul>

						</li>
						<li>
							<a href="/press">Press</a>
						</li>
						<li>
							<a href="/contact">Contact</a>
						</li>

					</ul>

					<!-- 					<ul class="nav navbar-nav navbar-right">
					<li>
					<a href="../about"> About</a>
					</li>
					</ul> -->
				</nav>
			</div>
		</header>

		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<%= yield %>
				</div>
			</div>
		</div>
		<!-- /container -->

	</body>
</html>

app/views/layouts/contact.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><%= content_for?(:title) ? yield(:title) : "Syllabus" %></title>
		<%= csrf_meta_tags %>

		<%= javascript_include_tag "application", :cache => false %>

		<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
		<!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
		<![endif]-->

		<%= stylesheet_link_tag "application", :media => "all" %>

		<!-- For third-generation iPad with high-resolution Retina display: -->
		<!-- Size should be 144 x 144 pixels -->
		<%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

		<!-- For iPhone with high-resolution Retina display: -->
		<!-- Size should be 114 x 114 pixels -->
		<%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

		<!-- For first- and second-generation iPad: -->
		<!-- Size should be 72 x 72 pixels -->
		<%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

		<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
		<!-- Size should be 57 x 57 pixels -->
		<%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

		<!-- For all other devices -->
		<!-- Size should be 32 x 32 pixels -->
		<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

	</head>

	<body>

		<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
			<div class="container">
				<div class="navbar-header">
					<button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a href="../" class="navbar-brand">Syllabus</a>
				</div>
				<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
					<ul class="nav navbar-nav">
						<li>
							<a href="#labels">Brand Philosophy</a>
						</li>
						<li>
							<a href="#badges">Designer</a>
						</li>

						<li class="<%= controller.controller_name == 'products' ? 'active' : '' %> dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Products <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li>
									<%= link_to "ALL", "/products" %>
								</li>
								<li class="divider"></li>
								<li>
									<%= link_to "EVENING CLUTCH", "/products?cat=clutch" %>
								</li>
								<li>
									<%= link_to "CONVERTIBLE CLUTCH", "/products?cat=clutch" %>
								</li>
								<li>
									<%= link_to "CONVERTIBLE TOTE SHOULDER", "/products?cat=tote" %>
								</li>
								<li>
									<%= link_to "BELTS", "/products?cat=belt" %>
								</li>
							</ul>

						</li>
						<li>
							<a href="/press">Press</a>
						</li>
						<li>
							<a href="/contact">Contact</a>
						</li>

					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="../about"> About</a>
						</li>
					</ul>
				</nav>
			</div>
		</header>

		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<%= yield %>

				</div>
			</div>
		</div>
		<!-- /container -->

	</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><%= content_for?(:title) ? yield(:title) : "Syllabus" %></title>
		<%= csrf_meta_tags %>

		<%= javascript_include_tag "application", :cache => false %>

		<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
		<!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
		<![endif]-->

		<%= stylesheet_link_tag "application", :media => "all" %>

		<!-- For third-generation iPad with high-resolution Retina display: -->
		<!-- Size should be 144 x 144 pixels -->
		<%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

		<!-- For iPhone with high-resolution Retina display: -->
		<!-- Size should be 114 x 114 pixels -->
		<%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

		<!-- For first- and second-generation iPad: -->
		<!-- Size should be 72 x 72 pixels -->
		<%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

		<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
		<!-- Size should be 57 x 57 pixels -->
		<%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

		<!-- For all other devices -->
		<!-- Size should be 32 x 32 pixels -->
		<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

	</head>

	<body>
		<div class="container" >
			<div class="row">
				<div class="col-md-12">
					<%= yield %>
				</div>
			</div>
		</div>
		<!-- /container -->

	</body>
</html>

app/views/products/_form.html.erb
<div class="row">
	<%= form_for @product, :html => { :class => 'form-vertical col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3' } do |f| %>
	
	<% if @product.id %>
	<div class="form-group">
		<%= f.label :id %>		
		<%= f.text_field :id, :class => 'form-control', :disabled => true %>		
	</div>
	<% end %>			

	<div class="form-group">
		<%= f.label :display_order %>
		<%= f.number_field :display_order, :class => 'form-control' %>
	</div>
	
	<div class="checkbox">
		<label>
			<%= f.check_box :hidden%>hidden
		</label>
	</div>
	
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, :class => 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :description, :class => 'control-label' %>
		<%= f.text_area :description, :class => 'form-control', :style => 'height:300px;' %>
	</div>
	
	<div class="form-group" style="display:none;">
		<%= f.label :price %>
		<div class="input-group">
			<span class="input-group-addon">$</span>
			<%= f.text_field :price, :class => 'form-control' %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :category %>
		<%
			cat_options = [
				[categoryTitle(100).titleize, 100], [categoryTitle(110).titleize, 110],
				[categoryTitle(200).titleize, 200], [categoryTitle(300).titleize, 300]
			]
		%>
		<%= f.select(:category, cat_options, {}, {:class => "form-control"}) %>
	</div>

	<div class="form-group">
		<%= f.label :season %>
		<%= f.text_field :season, :class => 'form-control' %>
	</div>

	<br/>

	<div class="form-actions">
		<%= f.submit nil, :class => 'btn btn-primary' %>
		<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
		product_path(@product), :class => 'btn' %>
	</div>
	<% end %>
</div>

<br/>

<% if @product.id %>
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">Detail Images<small><a href="/products/<%=@product.id%>/images"> edit</a></small></h3>
	</div>
	<div class="panel-body">
		<div class="row">
			<% @product.images.each.with_index(1) do |image, i| %>
			<div class="col-xs-3 col-md-3">
				<a href="/products/<%=@product.id%>/images/<%=i%>/edit" class="thumbnail"><%= image_tag image.image.url(:thumb) %></a>
			</div>
			<% end %>
		</div>				

	</div>
	<div class="panel-footer">

		<%= form_for([@product, @product.images.build]) do |f| %>
		<div class="control-group">
			<%= f.label 'add a image', :class => 'control-label' %>
			<div class="controls">
				<%= f.file_field :image, :class => 'file_field' %>
			</div>
		</div>
		
		<br/>

		<div class="form-actions">
			<%= f.submit nil, :class => 'btn btn-primary' %>
		</div>
		<% end %>
	</div>
</div>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>

<div class="panel panel-default">
	<div class="panel-body">

		<div class="page-header">
			<h1><%= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
		</div>
		<%= render :partial => 'form' %>

	</div>
</div>

app/views/products/index.html.erb
<%- model_class = Product -%>

<%
  cat = controller.params[:cat]
  season = controller.params[:season]
%>

<div class="panel panel-default">

	<div class="panel-heading">
		<h3>
			<%= categoryTitle(cat.to_i).pluralize.titleize %>
			<small>
				<span class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">
					<%= season == nil ? "All" : season %> <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="<%= products_path + (cat == nil ? "" : "?cat=" + cat) %>">All</a></li>
						<li class="divider"></li>
						<li><a href="<%= products_path%>?season=13/FW<%= cat == nil ? "" : "&cat=" + cat %>">13/FW</a></li>
						<li><a href="<%= products_path%>?season=14/SS<%= cat == nil ? "" : "&cat=" + cat %>">14/SS</a></li>
					</ul>
				</span>
			</small>
		</h3>
		<% if @_admin %>
		<%= link_to t('.new', :default => t("helpers.links.new")), new_product_path, :class => 'btn btn-primary' %>
		<% end %>
	</div>
	
	<div class="panel-body">
		<% @products.each.with_index(0) do |product, i| %>
		<% if(i%4 == 0) %>
		<div class="row">
		<% end %>
			<div class="product_list_item col-xs-12 col-sm-6 col-md-4 col-lg-3">
				<div class="thumbnail">
					<div class='product_img'>
						<% if product.images.length > 0 %>
						<%= link_to image_tag(product.images[0].image.url), product_path(product) %>
						<% end %>
					</div>
					<div class="caption">
						<h4 class="text-center"> <%= link_to product.name, product_path(product) %> </h4>
					</div>
				</div>
			</div>
		<% if(i%4 == 3) %>			
		</div>
		<% end %>
		<% end %>
	</div>
</div>

app/views/welcome/index.html.erb
<div id="intro">
	<%= link_to image_tag('intro.png', size: "900x600"), products_path %>
</div>